// The GitHub Pages root has no content of its own; the browser example lives
// under wasm/browser-example/. The root index must list every deployed example
// version so the site is navigable from its root, and CI must regenerate it on
// every Pages deployment.
import assert from "node:assert/strict";
import { mkdtemp, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import {
  generatePagesIndex,
  renderPagesIndex,
} from "../scripts/generate-pages-index.mjs";

var workflowPath = fileURLToPath(
  new URL("../../../.github/workflows/ci-wasm.yml", import.meta.url),
);

var versions = [
  { version: "dev", title: "dev", aliases: [] },
  { version: "1.1.0", title: "1.1.0", aliases: ["latest"] },
  { version: "1.0.0-beta.3", title: "1.0.0-beta.3", aliases: ["beta"] },
];

describe("PagesIndex", function () {
  var pagesRoot;

  beforeEach(async function () {
    pagesRoot = await mkdtemp(path.join(tmpdir(), "muhammara-pages-"));
  });

  afterEach(async function () {
    await rm(pagesRoot, { force: true, recursive: true });
  });

  it("links every deployed example version with its aliases", function () {
    var html = renderPagesIndex(versions);

    assert.match(html, /^<!doctype html>/);
    assert.match(html, /<title>MuhammaraJS<\/title>/);
    assert.match(html, /href="wasm\/browser-example\/index\.html"/);
    assert.match(html, /href="wasm\/browser-example\/dev\/index\.html">dev</);
    assert.match(
      html,
      /href="wasm\/browser-example\/1\.1\.0\/index\.html">1\.1\.0</,
    );
    assert.match(html, /<span class="alias">latest<\/span>/);
    assert.match(
      html,
      /href="wasm\/browser-example\/1\.0\.0-beta\.3\/index\.html"/,
    );
    assert.match(html, /<span class="alias">beta<\/span>/);
    assert.match(html, /https:\/\/muhammarajs\.readthedocs\.io\//);
    assert.match(html, /https:\/\/muhammarajs-wasm\.readthedocs\.io\//);
    assert.doesNotMatch(html, /No example has been deployed yet/);
  });

  it("escapes manifest text instead of injecting it into the page", function () {
    var html = renderPagesIndex([
      {
        version: "1.0.0",
        title: "<script>alert(1)</script>",
        aliases: ['a"b'],
      },
    ]);

    assert.doesNotMatch(html, /<script>alert/);
    assert.match(html, /&lt;script&gt;alert\(1\)&lt;\/script&gt;/);
    assert.match(html, /<span class="alias">a&quot;b<\/span>/);
  });

  it("writes index.html next to the example from the mike manifest", async function () {
    var exampleRoot = path.join(pagesRoot, "wasm", "browser-example");
    await mkdir(exampleRoot, { recursive: true });
    await writeFile(
      path.join(exampleRoot, "versions.json"),
      JSON.stringify(versions),
    );

    var indexPath = await generatePagesIndex(pagesRoot);

    assert.equal(indexPath, path.join(pagesRoot, "index.html"));
    assert.equal(await readFile(indexPath, "utf8"), renderPagesIndex(versions));
  });

  it("writes a page without versions before the first example deployment", async function () {
    await generatePagesIndex(pagesRoot);

    var html = await readFile(path.join(pagesRoot, "index.html"), "utf8");
    assert.match(html, /No example has been deployed yet/);
    assert.match(html, /href="wasm\/browser-example\/index\.html"/);
  });

  it("is regenerated by CI before every Pages deployment", async function () {
    var workflow = await readFile(workflowPath, "utf8");
    var uploads = workflow.split("actions/upload-pages-artifact@").length - 1;
    var generations = workflow.split("generate-pages-index.mjs").length - 1;

    assert.ok(uploads >= 2, "both deploy jobs upload a Pages artifact");
    assert.equal(generations, uploads);
    workflow
      .split("actions/upload-pages-artifact@")
      .slice(0, -1)
      .forEach(function (jobPrefix) {
        var checkout = jobPrefix.lastIndexOf("ref: gh-pages");
        var generation = jobPrefix.lastIndexOf("generate-pages-index.mjs");
        assert.ok(checkout >= 0, "the gh-pages branch is checked out");
        assert.ok(
          generation > checkout,
          "the root index is generated after the gh-pages checkout and before the upload",
        );
      });
  });
});
