/** Native Muhammara constants exposed by the WASM bridge. */
export var constants = {
  ePDFVersionUndefined: 0,
  ePDFVersion10: 10,
  ePDFVersion11: 11,
  ePDFVersion12: 12,
  ePDFVersion13: 13,
  ePDFVersion14: 14,
  ePDFVersion15: 15,
  ePDFVersion16: 16,
  ePDFVersion17: 17,
  ePDFVersion20: 20,
  KProcsetImageB: "ImageB",
  KProcsetImageC: "ImageC",
  KProcsetImageI: "ImageI",
  kProcsetPDF: "PDF",
  kProcsetText: "Text",
  eRangeTypeAll: 0,
  eRangeTypeSpecific: 1,
  ePDFPageBoxMediaBox: 0,
  ePDFPageBoxCropBox: 1,
  ePDFPageBoxBleedBox: 2,
  ePDFPageBoxTrimBox: 3,
  ePDFPageBoxArtBox: 4,
  ePDFObjectBoolean: 0,
  ePDFObjectLiteralString: 1,
  ePDFObjectHexString: 2,
  ePDFObjectNull: 3,
  ePDFObjectName: 4,
  ePDFObjectInteger: 5,
  ePDFObjectReal: 6,
  ePDFObjectArray: 7,
  ePDFObjectDictionary: 8,
  ePDFObjectIndirectObjectReference: 9,
  ePDFObjectStream: 10,
  ePDFObjectSymbol: 11,
  eTokenSeparatorSpace: 0,
  eTokenSeparatorEndLine: 1,
  eTokenSeparatorNone: 2,
  eXrefEntryExisting: 0,
  eXrefEntryDelete: 1,
  eXrefEntryStreamObject: 2,
  eXrefEntryUndefined: 3,
  EInfoTrappedTrue: 0,
  EInfoTrappedFalse: 1,
  EInfoTrappedUnknown: 2,
  getTypeLabel: function (type) {
    var labels = [
      "Boolean",
      "LiteralString",
      "HexString",
      "Null",
      "Name",
      "Integer",
      "Real",
      "Array",
      "Dictionary",
      "IndirectObjectReference",
      "Stream",
      "Symbol",
    ];
    if (!Number.isInteger(type) || type < 0 || type >= labels.length) {
      throw new TypeError(
        "Wrong arguments, provide a single enumerator value of a PDF Object type",
      );
    }
    return labels[type];
  },
};
