name: Build

on:
  push:
    tags:
      - '1.*'
    branches:
  pull_request:
  workflow_dispatch:
env:
  npm_version: 6.14.5

jobs:
  build-musl:
    strategy:
      fail-fast: true
      matrix:
        node: [6.14.1, 7.10.1, 8.11.0, 9.11.1, 10.8.0, 11.2.0, 12.0.0, 13.14.0, 14.0.0, 15.7.0]
    runs-on: ubuntu-latest
    container:
      image: node:${{ matrix.node }}-alpine
      credentials:
        username: "${{ secrets.DOCKER_USERNAME }}"
        password: "${{ secrets.DOCKER_PASSWORD }}"
    steps:
      - uses: actions/checkout@v2
      - run: apk update
      - run: apk add --no-cache make gcc jq g++ python tar
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: npm config set unsafe-perm true
      - run: npm -g install npm@^${{ env.npm_version }} --force
      - run: node --version
      - run: npm --version
      - run: npm install node-gyp@5.1.1 --global
      - run: npm install --build-from-source
        env:
          EXTRA_NODE_PRE_GYP_FLAGS: --target_libc=musl
      - run: npm run test
      - run: ./node_modules/.bin/node-pre-gyp package testpackage --target_libc=musl
      - uses: actions/upload-artifact@v2
        with:
          path: build/stage/julianhille/MuhammaraJS/releases/download/**/*.gz
          name: bindings
          if-no-files-found: error
  build-electron:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, macos-11.0, windows-2019]
        architecture: [x64, ia32, arm]
        electron: [13.0.0, 12.0.0, 11.4.7 ]
        include:
          - os: macos-11.0
            xcversion: 11.2.1
          - architecture: arm
            architecture_node: x64
            xcversion: 12.4
          - electron_mocha_version: ^10
          - architecture: ia32
            architecture_node: x86
          - architecture: x64
            architecture_node: x64
          - electron: 13.0.0
            node: 14.17.0
          - electron: 12.0.0
            node: 14.16.0
          - electron: 11.4.7
            node: 12
        exclude:
          - os: macos-11.0
            architecture: ia32
          - os: ubuntu-18.04
            architecture: arm
          - os: windows-2019
            architecture: arm
          - os: ubuntu-18.04
            architecture: ia32
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - run: xcversion select ${{ matrix.xcversion }} --symlink
        if: ${{ runner.os == 'macOS' }}
      - run: xcversion install-cli-tools
        if: ${{ runner.os == 'macOS' }}
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          architecture: ${{ matrix.architecture_node }}
      - run: npm -g install npm@^${{ env.npm_version }} --force
      - run: node --version
      - run: npm --version
      - run: npm install node-gyp@5.1.1 --global
      - run: npm config set msbuild_path "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe"
        if: ${{ runner.os == 'Windows' }}
      - run: npm install --build-from-source
        env:
          npm_config_arch: ${{ matrix.architecture }}
          npm_config_target_arch: ${{ matrix.architecture }}
          npm_config_target: ${{ matrix.electron }}
          npm_config_disturl: https://atom.io/download/electron
          npm_config_runtime: electron
      - run: npm install -g electron@${{ matrix.electron }} electron-mocha@${{ matrix.electron_mocha_version }}
      - name: Run test
        uses: GabrielBB/xvfb-action@v1
        with:
          working-directory: ./ #optional
          run: npm run test:electron
      - run: ./node_modules/.bin/node-pre-gyp package testpackage
        env:
          npm_config_runtime: electron
          npm_config_target: ${{ matrix.electron }}
      - uses: actions/upload-artifact@v2
        with:
          path: build/stage/julianhille/MuhammaraJS/releases/download/**/*.gz
          name: bindings
          if-no-files-found: error
  build-node:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, macos-11.0, windows-2019]
        node: [14.0.0, 15.7.0]
        architecture: [x64, ia32, arm]
        include:
          - architecture: ia32
            architecture_node: x86
          - architecture: x64
            architecture_node: x64
          - os: macos-11.0
            xcversion: 11.2.1
            architecture: x64
          - architecture: arm
            architecture_node: x64
            xcversion: 12.4
        exclude:
          - os: macos-11.0
            architecture: ia32
          - os: ubuntu-18.04
            architecture: ia32
          - os: ubuntu-18.04
            architecture: arm
          - os: windows-2019
            architecture: arm
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - run: xcversion select ${{ matrix.xcversion }} --symlink
        if: ${{ runner.os == 'macOS' }}
      - run: xcversion install-cli-tools
        if: ${{ runner.os == 'macOS' }}
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          architecture: ${{ matrix.architecture_node }}
      - run: npm -g install npm@^${{ env.npm_version }} --force
      - run: node --version
      - run: npm --version
      - run: npm install node-gyp@5.1.1 --global
      - run: npm config set msbuild_path "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe"
        if: ${{ runner.os == 'Windows' }}
      - run: npm install --build-from-source
        env:
          npm_config_arch: ${{ matrix.architecture }}
          npm_config_target_arch: ${{ matrix.architecture }}
      - run: ./node_modules/.bin/node-pre-gyp package testpackage
      - uses: actions/upload-artifact@v2
        with:
          path: build/stage/julianhille/MuhammaraJS/releases/download/**/*.gz
          name: bindings
          if-no-files-found: error
  publish:
    needs: [build-musl, build-electron, build-node]
    runs-on: ubuntu-latest
    if:  startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - uses: actions/download-artifact@v2
        with:
          name: bindings
          path: builds/bindings
        id: upload-release-asset
      - run: ls -lah builds/bindings/
      - name: Parse semver string
        id: semver_parser
        uses: booxmedialtd/ws-action-parse-semver@v1
        with:
          input_string: ${{ github.ref }}
          version_extractor_regex: 'tags\/(.*)$'
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.semver_parser.outputs.fullversion }}
          release_name: ${{ steps.semver_parser.outputs.fullversion }}
          draft: false
          prerelease: steps.semver_parser.outputs.prerelease != []
      - uses: AButler/upload-release-assets@v2.0
        with:
          files: 'builds/bindings/**/*'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          release-tag: ${{ steps.semver_parser.outputs.fullversion }}
      - run: npm install
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
