name: Linting

on:
  pull_request:
  workflow_call:

permissions:
  contents: read

jobs:
  prettier:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v6
      - name: Set up Node.js and restore npm cache
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: npm
      - run: npm ci --ignore-scripts
      - run: npm run test:codestyle
